#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '../public');
const check = process.argv.includes('--check');
const base = "default-src 'self'; script-src 'self' https://www.googletagmanager.com https://script.crazyegg.com https://static.cloudflareinsights.com HASHES; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://app.stayhustler.com https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com https://*.crazyegg.com https://cloudflareinsights.com; img-src 'self' data: https://*.google-analytics.com https://www.googletagmanager.com https://*.crazyegg.com; frame-src https://www.googletagmanager.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'";
const policies = new Map();
function visit(folder) {
    for (const entry of fs.readdirSync(path.join(root, folder), { withFileTypes: true })) {
        const relative = path.posix.join(folder, entry.name);
        if (entry.isDirectory()) { visit(relative); continue; }
        if (!entry.name.endsWith('.html')) continue;
        const html = fs.readFileSync(path.join(root, relative), 'utf8');
        const hashes = [...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(match => !/\bsrc=|application\/ld\+json/i.test(match[1])).map(match => "'sha256-" + crypto.createHash('sha256').update(match[2]).digest('base64') + "'");
        const policy = base.replace('HASHES', [...new Set(hashes)].join(' '));
        if (policy.length > 1800) throw new Error(`CSP too long: ${relative}`);
        policies.set('/' + relative, policy);
        policies.set('/' + relative.replace(/index\.html$/, '').replace(/\.html$/, ''), policy);
    }
}
visit('');
const output = '# Generated by scripts/build-headers.js. Edit HTML, then regenerate.\n/*\n  X-Frame-Options: DENY\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Cache-Control: no-cache\n\n' + [...policies].map(([route, policy]) => `${route}\n  Content-Security-Policy: ${policy}\n`).join('\n');
const file = path.join(root, '_headers');
if (check) { if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== output) { console.error('Static CSP headers need regeneration'); process.exitCode = 1; } }
else fs.writeFileSync(file, output);
// Apache applies the same policy by filename. index.html exists at two paths, so combine its hashes.
const byName = new Map();
for (const [route, policy] of policies) if (route.endsWith('.html')) {
    const name = path.basename(route);
    const hashes = policy.match(/'sha256-[^']+'/g) || [];
    byName.set(name, new Set([...(byName.get(name) || []), ...hashes]));
}
const block = '# BEGIN GENERATED CSP\n<IfModule mod_headers.c>\n' + [...byName].map(([name, hashes]) => `<Files "${name}">\n    Header always set Content-Security-Policy "${base.replace('HASHES', [...hashes].join(' '))}"\n</Files>`).join('\n') + '\n</IfModule>\n# END GENERATED CSP\n';
const apache = path.join(root, '.htaccess');
const old = fs.readFileSync(apache, 'utf8');
const expected = old.replace(/\n?# BEGIN GENERATED CSP[\s\S]*?# END GENERATED CSP\n?/, '').trimEnd() + '\n\n' + block;
if (check) { if (old !== expected) { console.error('Apache CSP needs regeneration'); process.exitCode = 1; } }
else fs.writeFileSync(apache, expected);
